debug: true

server:
  port: 9902

spring:
  profiles:
    active: local
    

mybatis:
  configuration:
    jdbc-type-for-null: "NULL"

ustra:
  core:
    cache:
      caffeine:
        authentication:
          maximum-size: 200 # 최대적재사이즈
          initial-capacity: 100 # 초기사이즈
          expire-after-write-seconds: 1800 # 캐시 적재 후 제거될 초수
          expire-after-access-seconds: 1800 # 캐시 조회 후 제거될 초수
  data:
    file:
      enabled: false
    procedure-manager:
      enabled: true
    datasource:
      default-datasource-name: rds1
      datasources:
        rds1:
          url: jdbc:log4jdbc:postgresql://172.28.31.140:15432/sample
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          username: sample
          password: P7YTWr+Z8z0UgcAu
    logging:
      interfaces:
        enabled: true
  mvc:
    view:
      api-prefix: api
      client-crypto-key: Z3NjLWNyeXB0by1rZXkxMQ==
      type: STATIC_THYEMELEAF
      
  sample:
    authentication: 
      secret-key: zjajhz829110y
      token-key: sample-fo-token
      enable-refresh-token: false
      access-valid-second: 1800
      allow-anonymous-authentication: true

---
spring:
  profiles:
    active: prd
ustra:
  data:
    datasource:
      datasources:
        rds1:
          url: jdbc:log4jdbc:postgresql://172.28.52.140:15432/sample
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          username: sample
          password: P7YTWr+Z8z0UgcAu