
debug: true

server:
  port: 9901

spring:
  profiles:
    active: local


mybatis:
  mapperLocations: classpath:/mapper/**/*.xml
  type-aliases-package: com.gsitm.ustra.java.management.models
  configuration:
    jdbc-type-for-null: "NULL"
   #   mapUnderscoreToCamelCase: true
   
 
ustra:
  core:
    process-info:
      default-system-code: BO
  data:
    procedure-manager:
      enabled: true
    datasource:
      default-datasource-name: rds1
      datasources:
        rds1:
          url: jdbc:log4jdbc:mysql://172.28.31.140:13306/ustra?useCursorFetch=true&zeroDateTimeBehavior=convertToNull&useSSL=false&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          username: ustra_admin
          password: Framework@2024
#          password: ENC(GAenXzlQvXW5Ckbr3U101A==)
    file:
      enabled: true
  mvc:
    view:
      api-prefix: api
      client-crypto-key: Z3NjLWNyeXB0by1rZXkxMQ==
      type: STATIC_THYEMELEAF
    rest:
      exclude-wrapping-url-patterns: /v2/api-docs,/swagger-resources/**,/swagger-ui.html,/webjars/**
    wrapper:
      exclude-request-url-patterns: /v2/api-docs
      exclude-response-url-patterns: /v2/api-docs
  management:
    bo:
      app:
        use-auth-approval: true
        use-user-approval: true
        password-change-days: 0
        maximum-auth-group-depth: 5
      authentication:
        allow-anoymous-authentication: true
        system-name: management-bo
        system-key: BO
        token-key: acc-token
        refresh-token-key: ref-token
        secret-key: asddflkhjasd
        enable-refresh-token: true
        refresh-valid-seconds: 6000
    

