
debug: true

server:
  port: 9901

spring:
  profiles:
    active: local


mybatis:
  mapperLocations: classpath:/mapper/**/*.xml,classpath:/mapper2/**/*.xml
  type-aliases-package: com.gsitm.ustra.java.management.models
  configuration:
    jdbc-type-for-null: "NULL"
   #   mapUnderscoreToCamelCase: true
   
---
spring:
  profiles: local
  
ustra:
  core:
    process-info:
      default-system-code: BO
    cache:
      map:
        additional-cache-names: USTRA-TEST-CACHE
      caffeine:
        caffeine-test:
          maximum-size: 200
          initial-capacity: 100
          # refresh-seconds: 600
          expire-after-write-seconds: 1800
          expire-after-access-seconds: 1800
        #eh:
        #  eh-test:
        #    config-location: classpath:/ehcache.xml
  data:
    procedure-manager:
      enabled: true
    datasource:
      default-datasource-name: rds1
      datasources:
        rds1:
          url: jdbc:log4jdbc:sqlserver://framework-sqlserver.c0uiyan5ae24.ap-northeast-2.rds.amazonaws.com:1433;databaseName=USTRA_FW_SPL
          driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
          username: ENC(p6rIPoShJklFLPxHKNJYFLooNCd2xnkayNZ2f+GexyA17qEMS77u8g==)
          password: ENC(ohS/a1/Q/lKriwUq3rqJqht76fQ0Bnge)
    file:
      enabled: true
      group:
        enabled: true
  mvc:
    view:
      api-prefix: api
      client-crypto-key: Z3NjLWNyeXB0by1rZXkxMQ==
      type: STATIC_THYEMELEAF
  management:
    bo:
      app:
        use-auth-approval: true
        use-user-approval: true
        password-change-days: 0
        maximum-auth-group-depth: 5
      authentication:
        allow-anoymous-authentication: true
        system-name: management-bo
        system-key: BO
        token-key: acc-token
        refresh-token-key: ref-token
        secret-key: asddflkhjasd
        enable-refresh-token: true
        refresh-valid-seconds: 6000
    

